name: ci
# see https://github.com/docker/build-push-action

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build EPICS 7.0.6.1 based on CentOS 7 and push
        uses: docker/build-push-action@v3
        with:
          file: ./epics/centos-7-epics-7.0.6.1/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: stephanecea/epics:centos-7-epics-7.0.6.1
